In [45]:
import torch
from d2l import torch as d2l
from torch import nn

In [46]:
def corr2d(X, K):
    """计算二维互相关性"""
    h, w = K.shape
    Y = torch.zeros((X.shape[0]-h+1), (X.shape[1]-w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i+h, j:j+w]*K).sum()
    return Y

边缘检测

In [47]:
X = torch.ones((6, 8))
X[:, 2:6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [48]:
K = torch.ones((1, 2))
K[0,1]=-1
K

tensor([[ 1., -1.]])

In [49]:
Y = corr2d(X, K)
Y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

对卷积核进行学习

In [50]:
net = nn.Conv2d(1, 1, kernel_size=(1,2), bias=False)
X = X.reshape(1, 1, 6, 8)
Y = Y.reshape(1, 1, 6, 7)

loss = nn.MSELoss()
trainer = torch.optim.SGD(net.parameters(), lr=0.1)


In [51]:

for i in range(15):
    l = loss(net(X), Y)
    trainer.zero_grad()
    l.backward()
    trainer.step()

    print(f'epoch{i+1}, loss={l.sum()}')


epoch1, loss=0.1013103798031807
epoch2, loss=0.09348493814468384
epoch3, loss=0.08666246384382248
epoch4, loss=0.08063728362321854
epoch5, loss=0.07525495439767838
epoch6, loss=0.0703987255692482
epoch7, loss=0.06597983837127686
epoch8, loss=0.061930179595947266
epoch9, loss=0.05819704011082649
epoch10, loss=0.05473911762237549
epoch11, loss=0.051523707807064056
epoch12, loss=0.048524465411901474
epoch13, loss=0.04571991786360741
epoch14, loss=0.0430922694504261
epoch15, loss=0.04062652960419655


In [55]:
net.state_dict()

OrderedDict([('weight', tensor([[[[ 0.6260, -0.6426]]]]))])